routes:
- name: root_servlet
  path: /
  handler: WebService\RootHandler
  method:
    - GET
    - POST
- name: swagger_servlet
  path: /api/docs
  handler: WebService\ApiHandler
  requiredPermission: API
  method:
    - GET
- name: swagger_servlet_ui
  path: /api/swagger-ui
  handler: WebService\SwaggerUiHandler
  requiredPermission: API
  method:
  - GET