#!/usr/bin/php
<?php
/** @noinspection ALL */

use Console\AddRoleCommand;
use Console\CheckAccess;
use Console\ConfigureRoleCommand;
use Console\ServerCommand;
use Globals\DB;
use Symfony\Component\Console\Application;

/** @noinspection PhpIncludeInspection */

include_once __DIR__ . '/bootstrap/globals.php';
include_once __DIR__ . '/../vendor/autoload.php';
include_once __DIR__ . "/config.php";

define("__ROOT__", __DIR__);

include_once __DIR__ . '/bootstrap/classloader.php';
include_once __DIR__ . '/bootstrap/init.php';

Globals\ConfigurationManager::getInstance()->init();

DB::getInstance()->load(envvar("PROFILE", "dev"));

$app = new Application();

$app->add(new ServerCommand());
$app->add(new AddRoleCommand());
$app->add(new ConfigureRoleCommand());
$app->add(new CheckAccess());

$app->run();