#!/usr/bin/php
<?php
/** @noinspection ALL */

use Doctrine\Common\Annotations\AnnotationRegistry;

/** @noinspection PhpIncludeInspection */

include_once __DIR__ . '/bootstrap/globals.php';
include_once __DIR__ . '/../vendor/autoload.php';

/**
 * Class ClassLoader
 */
class SubClassLoader {

    private static $loaders = array();

    public static function add (Closure $closure) {
        array_push(self::$loaders, $closure);
    }

    public static function init () {
        $loader = function ($name) {
            if (!class_exists($name)) {
                foreach (self::$loaders as $v) {
                    $v($name);

                    if (class_exists($name)) return TRUE;
                }
            }
            else {
                return TRUE;
            }

            return FALSE;
        };

        spl_autoload_register($loader);

        AnnotationRegistry::registerLoader($loader);
    }
}

SubClassLoader::add(function ($name) {

    $pathCorrect = function ($path, $replace = "/") {
        $str = str_replace("\\", $replace, $path);
        return str_replace("/", $replace, $str);
    };

    $cacheLocation    = envvar("SYSTEM_PLUMBOK_LOCATION", __DIR__ . "/../cache/");
    $cacheEnabled     = toBool(envvar("SYSTEM_PLUMBOK_CACHE_ENABLED", "true"));
    $plumbokEnabled   = toBool(envvar("SYSTEM_PLUMBOK_ENABLED", "true"));
    $plumbokOverwrite = toBool(envvar("SYSTEM_PLUMBOK_OVERWRITE_ORIGINAL", "true"));

    if (!file_exists($cacheLocation)) mkdir($cacheLocation);

    $phpFile   = __DIR__ . "/lib/" . $pathCorrect($name) . ".php";
    $cacheFile = $cacheLocation . $pathCorrect($name, "_") . ".php";

    /**
     * Include Cached-File :)
     */
    if ($cacheEnabled && $plumbokEnabled && file_exists($cacheFile)) {
        include_once $cacheFile;
        return;
    }

    if (file_exists($phpFile)) {
        if ($plumbokEnabled) {
            try {
                $plumbokCompiler = new Compiler();
                $nodes           = $plumbokCompiler->compile($phpFile);
                $serialize       = new Standard();
                $fileContent     = $serialize->prettyPrint($nodes);

                /**
                 * Include source file if plumbok could not create a class
                 */
                if (empty(trim($fileContent))) {
                    include_once $phpFile;
                    return;
                }

                file_put_contents($cacheFile, "<?php \n\n" . $fileContent);

                if ($plumbokOverwrite) {
                    $tagsUpdater = new TagsUpdater(new NodeFinder());
                    $tagsUpdater->applyNodes($phpFile, ...$nodes);
                }

                include_once $cacheFile;
            } catch (InvalidArgumentException $e) {
                include_once $phpFile;
            } catch (Error $e) {
                include_once $phpFile;
            }
        }
        else {
            include_once $phpFile;
        }
    }
});

SubClassLoader::init();

$app = new \Symfony\Component\Console\Application();

$app->add(new \Console\ServerCommand());

$app->run();