#!/usr/bin/php
<?php
/** @noinspection ALL */

use Doctrine\Common\Annotations\AnnotationRegistry;

/** @noinspection PhpIncludeInspection */

include_once __DIR__ . '/bootstrap/globals.php';
include_once __DIR__ . '/../vendor/autoload.php';

define("__ROOT__", __DIR__);

include_once __DIR__ . '/bootstrap/classloader.php';

ClassLoader::init();

$app = new \Symfony\Component\Console\Application();

$app->add(new \Console\ServerCommand());

$app->run();